name: Deploy to gh-pages
  
on:
  push:
    branches: [ main, revamp, tutorials ]
  pull_request:
    branches: [ main, revamp, tutorials  ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3

      - name: install and build
        run: |
          cd deepchem
          npm i
          npm run export
          cd out
          touch .nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deepchem/out
          branch: gh-pages
          clean-exclude: |
            .nojekyll
            CNAME
